apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestaoutilizadores
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestaoutilizadores
  template:
    metadata:
      labels:
        app: gestaoutilizadores
    spec:
      containers:
        - name: gestaoutilizadores
          image: diogofilipe7/gestaoutilizadores:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gestaoutilizadores
  namespace: default
  selfLink: /api/v1/namespaces/default/services/gestaoutilizadores
spec:
  clusterIP: 10.99.146.173
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31807
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: gestaoutilizadores
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
